//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correlation
    {
        public int Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int UserInPool1_Id { get; set; }
        public int UserInPool2_Id { get; set; }
    
        public virtual UserInPool UserInPool { get; set; }
        public virtual UserInPool UserInPool1 { get; set; }
    }
}
