//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamDb6Entities : DbContext
    {
        public TeamDb6Entities()
            : base("name=TeamDb6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Criteria> Criteria { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Generator> Generator { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Invitaton> Invitaton { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
        public virtual DbSet<UserInCategory> UserInCategory { get; set; }
        public virtual DbSet<UserInGroup> UserInGroup { get; set; }
        public virtual DbSet<UserInTeam> UserInTeam { get; set; }
        public virtual DbSet<UserOnEvent> UserOnEvent { get; set; }
        public virtual DbSet<UserVoting> UserVoting { get; set; }
        public virtual DbSet<Voting> Voting { get; set; }
        public virtual DbSet<VotingLog> VotingLog { get; set; }
    }
}
