//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamDb3Entities : DbContext
    {
        public TeamDb3Entities()
            : base("name=TeamDb3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Correlation> Correlation { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Pool> Pool { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<ScoreHistory> ScoreHistory { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectInPool> SubjectInPool { get; set; }
        public virtual DbSet<SubjectTeamEvent> SubjectTeamEvent { get; set; }
        public virtual DbSet<Team> Team { get; set; }
    }
}
