//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOnEvent
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public int UserCategoryId { get; set; }
        public Nullable<int> VoteCounter { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Team Team { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
