//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVoting
    {
        public int Id { get; set; }
        public int VotingId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> VoteCounter { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Loses { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Voting Voting { get; set; }
    }
}
