//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVoting
    {
        public int Id { get; set; }
        public string VotingId { get; set; }
        public int VoteCounter { get; set; }
        public int Wins { get; set; }
        public int Loses { get; set; }
        public int Draws { get; set; }
        public int UserOnEventId { get; set; }
    
        public virtual UserOnEvent UserOnEvent { get; set; }
        public virtual Voting Voting { get; set; }
    }
}
