//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOnEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserOnEvent()
        {
            this.UserInTeam = new HashSet<UserInTeam>();
            this.UserVoting = new HashSet<UserVoting>();
        }
    
        public int Id { get; set; }
        public int UserInCategoryId { get; set; }
        public int EventId { get; set; }
        public int PositionId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Position Position { get; set; }
        public virtual UserInCategory UserInCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInTeam> UserInTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVoting> UserVoting { get; set; }
    }
}
