//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGeneratorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voting()
        {
            this.UserVoting = new HashSet<UserVoting>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int EventId { get; set; }
        public Nullable<System.DateTime> StartVoting { get; set; }
        public Nullable<System.DateTime> FinishVoting { get; set; }
        public bool Active { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVoting> UserVoting { get; set; }
    }
}
